import { useState, useEffect, useRef, useLayoutEffect } from 'react';
import {
  ContentCopy as CopyIcon,
  RefreshOutlined as RefreshIcon,
} from '@mui/icons-material';
import jobPostingService from '../../services/jobPostingService';

function JobDescription({ formData, handleChange }) {
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);
  const [aiContext, setAiContext] = useState('');
  const [showAISuccess, setShowAISuccess] = useState(false);
  const [copied, setCopied] = useState(false);

  // 🔑 Refs
  const textareaRef = useRef(null);
  const typingIntervalRef = useRef(null);
  const isUserAtBottomRef = useRef(true);
  const hasAutoGeneratedRef = useRef(false); // ⭐ IMPORTANT

  const handleAiContextChange = (e) => {
    setAiContext(e.target.value);
  };

  /* ---------------- CHATGPT STYLE TYPING ---------------- */

  const typeTextWordByWord = (text, speed = 70) => {
    if (typingIntervalRef.current) {
      clearInterval(typingIntervalRef.current);
    }

    const words = text.split(' ');
    let index = 0;
    let currentText = '';

    handleChange('job_description', '');

    typingIntervalRef.current = setInterval(() => {
      currentText += (index === 0 ? '' : ' ') + words[index];
      handleChange('job_description', currentText);

      index++;
      if (index >= words.length) {
        clearInterval(typingIntervalRef.current);
        typingIntervalRef.current = null;
      }
    }, speed);
  };

  /* ---------------- AUTO SCROLL (CHATGPT BEHAVIOR) ---------------- */

  const handleScroll = () => {
    const el = textareaRef.current;
    if (!el) return;

    const threshold = 10;
    isUserAtBottomRef.current =
      el.scrollHeight - el.scrollTop - el.clientHeight < threshold;
  };

  useLayoutEffect(() => {
    const el = textareaRef.current;
    if (!el || !isUserAtBottomRef.current) return;

    requestAnimationFrame(() => {
      el.scrollTop = el.scrollHeight;
    });
  }, [formData.job_description]);

  /* ---------------- GENERATE JD ---------------- */

  const generateJobDescription = async () => {
    try {
      setLoading(true);
      setError(null);
      setShowAISuccess(false);

      const jobData = {
        job_title: formData.job_title,
        company: formData.company,
        job_type: formData.job_type,
        work_location: formData.work_location,
        required_skills: Array.isArray(formData.required_skills)
          ? formData.required_skills.join(', ')
          : '',
        experience_level: Array.isArray(formData.requirements)
          ? formData.requirements.join(', ')
          : '',
        responsibilities: Array.isArray(formData.responsibilities)
          ? formData.responsibilities.join('\n')
          : '',
        qualifications: formData.qualifications || '',
        job_description: '',
        additional_context: aiContext
      };

      const response =
        await jobPostingService.generateJobDescription(jobData);
      isUserAtBottomRef.current = true;
      typeTextWordByWord(response.job_description);
      setShowAISuccess(true);
    } catch (err) {
      console.error(err);
      setError('Access Denied.');
    } finally {
      setLoading(false);
    }
  };

  /* ---------------- AUTO GENERATE (ONCE ONLY) ---------------- */

  useEffect(() => {
    if (
      !hasAutoGeneratedRef.current &&
      formData.use_ai_generation &&
      formData.job_title &&
      formData.company
    ) {
      hasAutoGeneratedRef.current = true;
      generateJobDescription();
    }
  }, []);

  /* ---------------- UI ---------------- */

  return (
    <div className="bg-white rounded-lg">
      {/* Header */}
      <div className="flex justify-between items-center mb-4 px-6 pt-6">
        <h2 className="text-lg font-semibold text-gray-900">
          Job Description
        </h2>

        <div className="flex gap-2 items-center relative">
          <button
            className="p-2 text-gray-600 hover:bg-gray-100 rounded-md"
            onClick={async () => {
              try {
                await navigator.clipboard.writeText(
                  formData.job_description || ''
                );
                setCopied(true);
                setTimeout(() => setCopied(false), 2000);
              } catch (err) {
                console.error('Failed to copy: ', err);
              }
            }}
          >
            <CopyIcon className="w-5 h-5" />
          </button>
          
          {/* Visible copy notification popup */}
          {copied && (
            <div className="absolute -top-10 left-0 bg-green-600 text-white px-3 py-1 rounded-md text-sm font-medium shadow-md z-10 animate-fade-in-out">
              ✓ Copied to clipboard!
            </div>
          )}

          <button
            className="px-3 py-1 text-xs border rounded"
            onClick={() => handleChange('currentStep', 1)}
          >
            ← Back
          </button>
        </div>
      </div>

      {/* Textarea */}
      <div className="px-6">
        <textarea
          ref={textareaRef}
          value={formData.job_description || ''}
          onScroll={handleScroll}
          onChange={(e) => {
            if (typingIntervalRef.current) {
              clearInterval(typingIntervalRef.current);
              typingIntervalRef.current = null;
            }
            handleChange('job_description', e.target.value);
          }}
          className="
            w-full
            h-[320px]
            border
            rounded-lg
            p-4
            text-sm
            resize-none
            overflow-y-auto
            focus:outline-none
          "
          placeholder={loading ? 'Generating job description...' : ''}
        />
      </div>

      {/* AI Controls */}
      <div className="px-6 pb-6 mt-4">
        <div className="flex gap-2">
          <input
            type="text"
            placeholder="Add additional context for AI"
            className="flex-1 px-4 py-2 border rounded text-sm"
            value={aiContext}
            onChange={handleAiContextChange}
            disabled={loading}
          />

          <button
            onClick={generateJobDescription}
            disabled={loading}
            className="px-6 py-2 bg-gray-700 text-white rounded disabled:bg-gray-400 flex items-center gap-2"
          >
            <RefreshIcon
              className={`w-4 h-4 ${loading ? 'animate-spin' : ''}`}
            />
            Generate
          </button>
        </div>

        {error && (
          <div className="mt-3 p-3 bg-red-50 border text-red-700 text-sm rounded">
            {error}
          </div>
        )}

        {showAISuccess && (
          <div className="mt-3 p-3 bg-green-50 border text-green-700 text-sm rounded">
            ✓ Job description generated successfully!
          </div>
        )}
      </div>
    </div>
  );
}

export default JobDescription;
